#!/bin/sh

#          Remarks: A line beginning with # is a comment.
#          A line beginning with #PBS is a PBS directive.
#          PBS directives must come first; any directives
#          after the first executable statement are ignored.

#PBS -N pcp_tp1
#PBS -l walltime=00:05:00
#PBS -q mei

#          PBS can send informative email messages to you about the
#          status of your job.  Specify a string which consists of
#          either the single character "n" (no mail), or one or more
#          of the characters "a" (send mail when job is aborted),
#          "b" (send mail when job begins), and "e" (send mail when
#          job terminates).  The default is "a" if not specified.
#          You should also specify the email address to which the
#          message should be send via the -M option.

#PBS -m abe
#PBS -M a57816@alunos.uminho.pt

#          Specify the number of nodes requested and the
#          number of processors per node. 

#PBS -l nodes=1:ppn=24

module purge
module load gnu/4.9.0
echo "Done Loading Modules..."

cd PCP_Project

echo "Compiling..."
make clean
make

echo "Running 10 sequential..."
./bin/pcp_tp1_seq
./bin/pcp_tp1_seq
./bin/pcp_tp1_seq
./bin/pcp_tp1_seq
./bin/pcp_tp1_seq
./bin/pcp_tp1_seq
./bin/pcp_tp1_seq
./bin/pcp_tp1_seq
./bin/pcp_tp1_seq
./bin/pcp_tp1_seq
./bin/pcp_tp1_seq

echo "Running 10 parallel (2 threads)..."
./bin/pcp_tp1_par 2
./bin/pcp_tp1_par 2
./bin/pcp_tp1_par 2
./bin/pcp_tp1_par 2
./bin/pcp_tp1_par 2
./bin/pcp_tp1_par 2
./bin/pcp_tp1_par 2
./bin/pcp_tp1_par 2
./bin/pcp_tp1_par 2
./bin/pcp_tp1_par 2

echo "Running 10 parallel (4 threads)..."
./bin/pcp_tp1_par 4
./bin/pcp_tp1_par 4
./bin/pcp_tp1_par 4
./bin/pcp_tp1_par 4
./bin/pcp_tp1_par 4
./bin/pcp_tp1_par 4
./bin/pcp_tp1_par 4
./bin/pcp_tp1_par 4
./bin/pcp_tp1_par 4
./bin/pcp_tp1_par 4

echo "Running 10 parallel (6 threads)..."
./bin/pcp_tp1_par 6
./bin/pcp_tp1_par 6
./bin/pcp_tp1_par 6
./bin/pcp_tp1_par 6
./bin/pcp_tp1_par 6
./bin/pcp_tp1_par 6
./bin/pcp_tp1_par 6
./bin/pcp_tp1_par 6
./bin/pcp_tp1_par 6
./bin/pcp_tp1_par 6

echo "Running 10 parallel (8 threads)..."
./bin/pcp_tp1_par 8
./bin/pcp_tp1_par 8
./bin/pcp_tp1_par 8
./bin/pcp_tp1_par 8
./bin/pcp_tp1_par 8
./bin/pcp_tp1_par 8
./bin/pcp_tp1_par 8
./bin/pcp_tp1_par 8
./bin/pcp_tp1_par 8
./bin/pcp_tp1_par 8

echo "Running 10 parallel (10 threads)..."
./bin/pcp_tp1_par 10
./bin/pcp_tp1_par 10
./bin/pcp_tp1_par 10
./bin/pcp_tp1_par 10
./bin/pcp_tp1_par 10
./bin/pcp_tp1_par 10
./bin/pcp_tp1_par 10
./bin/pcp_tp1_par 10
./bin/pcp_tp1_par 10
./bin/pcp_tp1_par 10

echo "Running 10 parallel (12 threads)..."
./bin/pcp_tp1_par 12
./bin/pcp_tp1_par 12
./bin/pcp_tp1_par 12
./bin/pcp_tp1_par 12
./bin/pcp_tp1_par 12
./bin/pcp_tp1_par 12
./bin/pcp_tp1_par 12
./bin/pcp_tp1_par 12
./bin/pcp_tp1_par 12
./bin/pcp_tp1_par 12
echo "Done..."

